FROM node:18 AS client
WORKDIR app/client
COPY . .
RUN npm install
RUN npm run clean
ARG BASEURL
ENV BASEURL=$BASEURL
ARG PUBLIC_KEY
ENV PUBLIC_KEY=$PUBLIC_KEY
RUN npm run build

FROM node:18
# Forcer le faite d'utiliser les miroirs français quand on utilise apt ...
# Attention, le chemin source est rélative à l'emplacement du fichier docker-compose
COPY ./docker/sources.list /etc/apt/sources.list
COPY --from=client /app/client ./client
# Créer l'utilisateur et son groupe, installer des paquets
RUN apt-get update \        
    && apt-get install -y sudo \
    && apt-get install -y less \
    && apt-get install -y mycli \
    && apt-get install -y tzdata \ 
    && apt-get install -y ssh \   
    && npm install -g typescript \
    && npm install -g ts-node

# Fixer le fuseau horaire
ENV TZ Europe/Paris

# L'interprète par défaut
ENV SHELL /bin/bash

# Le repertoire maison par défaut
WORKDIR /home/dev

RUN /bin/bash