FROM node:18-alpine AS api-builder
WORKDIR app
COPY . .
RUN npm install
RUN npm run clean
RUN npm run build

FROM node:18-alpine AS api
WORKDIR app
COPY --from=api-builder /app/build ./
COPY --from=api-builder /app/secrets ./secrets
COPY --from=api-builder /app/.ssh ./.ssh
COPY --from=api-builder /app/client ./client

COPY package* ./
RUN npm install --omit=dev
CMD npm run start-api
